// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXl6Fghc2NmyKJ3hDrJpXFf7EisdU6sCs',
    appId: '1:124686715238:web:df38fd62763b8c3e2ca0a7',
    messagingSenderId: '124686715238',
    projectId: 'plant-identifier-android-1abb5',
    authDomain: 'plant-identifier-android-1abb5.firebaseapp.com',
    storageBucket: 'plant-identifier-android-1abb5.firebasestorage.app',
    measurementId: 'G-GCD82SS1K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATuqWsZ4qocX98k_ez05iSPvKMyuK98HY',
    appId: '1:124686715238:android:e129d960971a09132ca0a7',
    messagingSenderId: '124686715238',
    projectId: 'plant-identifier-android-1abb5',
    storageBucket: 'plant-identifier-android-1abb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJh-x3TjUeyDLUC0TryxdtXPoNseLhSds',
    appId: '1:124686715238:ios:6794cca1c7bb51072ca0a7',
    messagingSenderId: '124686715238',
    projectId: 'plant-identifier-android-1abb5',
    storageBucket: 'plant-identifier-android-1abb5.firebasestorage.app',
    iosBundleId: 'com.example.pi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJh-x3TjUeyDLUC0TryxdtXPoNseLhSds',
    appId: '1:124686715238:ios:6794cca1c7bb51072ca0a7',
    messagingSenderId: '124686715238',
    projectId: 'plant-identifier-android-1abb5',
    storageBucket: 'plant-identifier-android-1abb5.firebasestorage.app',
    iosBundleId: 'com.example.pi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXl6Fghc2NmyKJ3hDrJpXFf7EisdU6sCs',
    appId: '1:124686715238:web:8361460bf1acae8b2ca0a7',
    messagingSenderId: '124686715238',
    projectId: 'plant-identifier-android-1abb5',
    authDomain: 'plant-identifier-android-1abb5.firebaseapp.com',
    storageBucket: 'plant-identifier-android-1abb5.firebasestorage.app',
    measurementId: 'G-6ZMY6W5SV6',
  );
}
